# Generated by Django 5.0.6 on 2024-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_updated',
            field=models.BooleanField(default=False),
        ),
    ]
