# Generated by Django 5.0.6 on 2024-06-06 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_certification_education_project_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_url',
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
